name: anki_clone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  connectivity_plus: ^7.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.0.3
  path: ^1.9.1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.0
  supabase_flutter: ^2.12.0
  uuid: ^4.5.2
  sqlite3_flutter_libs: ^0.5.41
  flutter_inappwebview: ^6.1.5
  universal_platform: ^1.0.0+1
  webview_windows: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - .env
  uses-material-design: true
